clean2:
	-$(RM) $(CC_DEPS)$(C++_DEPS)$(C_UPPER_DEPS)$(CXX_DEPS)$(SECONDARY_FLASH)$(SECONDARY_SIZE)$(ASM_DEPS)$(S_UPPER_DEPS)$(C_DEPS)$(CPP_DEPS)
	-$(RM) $(OBJS) *.elf
	-@echo ' '


*.elf: $(wildcard F:/Users/xqyjlj/Documents/GitHub/STM32-RT_Thread-link_H750/boot/art_pi_bootloader/board/linker_scripts/STM32H750XBHx/link.lds)
